language: node_js
node_js:
    - '8'

cache:
    directories:
        - 'node_modules'

branches:
    only:
        - master

install:
    - npm install
    - npm run build

script:
    - npm test
    - npm test:e2e

deploy:
    provider: pages
    skip-cleanup: true
    github-token: $GITHUB_ACCESS_TOKEN
    target-branch: gh-pages
    local-dir: build
    on:
        branch: master
