export const FETCH_TAROT_REQUEST = 'FETCH_TAROT_REQUEST';
export const FETCH_TAROT_SUCCESS = 'FETCH_TAROT_SUCCESS';
export const FETCH_TAROT_ERROR = 'FETCH_TAROT_ERROR';
export const CLOSE_CARDS = 'CLOSE_CARDS';
export const SORT_CARDS = 'SORT_CARDS';
